{{- if .Values.apiAuthentication.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-authentication
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-authentication
  {{- with .Values.apiAuthentication.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: "5000"
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: api-authentication
{{- end }}

