apiVersion: v2
name: kbot-self-hosted
description: A Helm chart for Kbot self-hosted installation including all microservices
type: application
version: 0.2.0
appVersion: "1.0"
keywords:
  - kbot
  - konverso
maintainers:
  - name: Konverso Team
dependencies:
  - name: clamav
    version: 3.7.1
    repository: https://wiremind.github.io/wiremind-helm-charts