{{- if .Values.apiAuthAntivirus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-auth-antivirus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-auth-antivirus
  {{- with .Values.apiAuthAntivirus.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: actuator
      port: 8090
      protocol: TCP
      targetPort: 8090
    - name: apirest
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: api-auth-antivirus
{{- end }}

